import {
  AlignFeature,
  BlockquoteFeature,
  BoldFeature,
  ChecklistFeature,
  EXPERIMENTAL_TableFeature,
  FixedToolbarFeature,
  HeadingFeature,
  HorizontalRuleFeature,
  IndentFeature,
  InlineCodeFeature,
  InlineToolbarFeature,
  ItalicFeature,
  LinkFeature,
  OrderedListFeature,
  ParagraphFeature,
  StrikethroughFeature,
  SubscriptFeature,
  SuperscriptFeature,
  TextStateFeature,
  UnderlineFeature,
  UnorderedListFeature,
  lexicalEditor,
} from '@payloadcms/richtext-lexical'

export const seoContentLexical = lexicalEditor({
  features: [
    HeadingFeature({ enabledHeadingSizes: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'] }),
    ParagraphFeature(),
    BoldFeature(),
    ItalicFeature(),
    UnderlineFeature(),
    StrikethroughFeature(),
    OrderedListFeature(),
    UnorderedListFeature(),
    ChecklistFeature(),
    BlockquoteFeature(),
    AlignFeature(),
    IndentFeature(),
    HorizontalRuleFeature(),
    InlineCodeFeature(),
    SubscriptFeature(),
    SuperscriptFeature(),
    EXPERIMENTAL_TableFeature(),
    LinkFeature({ enabledCollections: ['pages', 'posts'] }),
    TextStateFeature({
      state: {
        fontSize: {
          '12px': { label: '12px', css: { 'font-size': '12px' } },
          '13px': { label: '13px', css: { 'font-size': '13px' } },
          '14px': { label: '14px', css: { 'font-size': '14px' } },
          '15px': { label: '15px', css: { 'font-size': '15px' } },
          '16px': { label: '16px', css: { 'font-size': '16px' } },
          '18px': { label: '18px', css: { 'font-size': '18px' } },
          '20px': { label: '20px', css: { 'font-size': '20px' } },
          '24px': { label: '24px', css: { 'font-size': '24px' } },
          '28px': { label: '28px', css: { 'font-size': '28px' } },
          '32px': { label: '32px', css: { 'font-size': '32px' } },
          '36px': { label: '36px', css: { 'font-size': '36px' } },
          '48px': { label: '48px', css: { 'font-size': '48px' } },
        },
      },
    }),
    FixedToolbarFeature(),
    InlineToolbarFeature(),
  ],
})
