import { revalidateTag, revalidatePath } from 'next/cache'
import { NextRequest, NextResponse } from 'next/server'

/**
 * On-demand revalidation endpoint.
 *
 * Authentication: Requires `REVALIDATE_SECRET` env var. If unset, the
 * endpoint refuses all requests with 503 (we never want to ship an open
 * revalidation endpoint to production by accident).
 *
 * Usage:
 *   POST /api/revalidate
 *   Body: { secret: "...", tag?: "global_home", path?: "/blog/some-post" }
 *
 *   GET /api/revalidate?secret=...&path=/blog/foo
 *   GET /api/revalidate?secret=...&tag=global_home
 *   GET /api/revalidate?secret=...               // revalidate all
 *
 * Multiple tags/paths can be supplied as comma-separated values.
 */

const REVALIDATE_SECRET = process.env.REVALIDATE_SECRET

// All globals registered in payload.config.ts. Keep in sync if you add more.
const ALL_GLOBAL_TAGS = [
  'global_home',
  'global_about',
  'global_blog',
  'global_contact',
  'global_portfolio',
  'global_cost-estimator-settings',
  'global_header',
  'global_footer',
] as const

// The main index/listing paths that aggregate collection content.
const COLLECTION_INDEX_PATHS = [
  '/',
  '/blog',
  '/portfolio',
  '/services',
  '/service-areas',
  '/sitemap',
] as const

// Sitemap/robots/llms — get regenerated by a full revalidate.
const SITE_LEVEL_PATHS = [
  '/sitemap.xml',
  '/image-sitemap.xml',
  '/llms.txt',
  '/llms-full.txt',
] as const

function requireSecret(provided: string | null | undefined): NextResponse | null {
  if (!REVALIDATE_SECRET) {
    return NextResponse.json(
      {
        error:
          'REVALIDATE_SECRET is not configured. Refusing to revalidate. Set REVALIDATE_SECRET in .env and restart.',
      },
      { status: 503 },
    )
  }
  if (provided !== REVALIDATE_SECRET) {
    return NextResponse.json({ error: 'Invalid secret' }, { status: 401 })
  }
  return null
}

function splitList(value: string | undefined | null): string[] {
  if (!value) return []
  return value
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)
}

function revalidateAll(items: string[]): void {
  for (const tag of ALL_GLOBAL_TAGS) {
    revalidateTag(tag)
    items.push(`tag:${tag}`)
  }
  // Site-wide LLMs cache (drives /llms.txt and /llms-full.txt content).
  revalidateTag('llms-txt')
  items.push('tag:llms-txt')

  for (const path of [...COLLECTION_INDEX_PATHS, ...SITE_LEVEL_PATHS]) {
    revalidatePath(path)
    items.push(`path:${path}`)
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json().catch(() => ({}))
    const secret: string | undefined = body?.secret
    const tagInput: string | string[] | undefined = body?.tag
    const pathInput: string | string[] | undefined = body?.path

    const secretError = requireSecret(secret)
    if (secretError) return secretError

    const items: string[] = []

    const tags = Array.isArray(tagInput)
      ? tagInput
      : splitList(typeof tagInput === 'string' ? tagInput : undefined)
    const paths = Array.isArray(pathInput)
      ? pathInput
      : splitList(typeof pathInput === 'string' ? pathInput : undefined)

    for (const tag of tags) {
      revalidateTag(tag)
      items.push(`tag:${tag}`)
    }
    for (const path of paths) {
      revalidatePath(path)
      items.push(`path:${path}`)
    }

    if (tags.length === 0 && paths.length === 0) {
      revalidateAll(items)
    }

    return NextResponse.json({
      success: true,
      revalidated: true,
      items,
      count: items.length,
      timestamp: new Date().toISOString(),
    })
  } catch (error) {
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to revalidate',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 },
    )
  }
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const secret = searchParams.get('secret')

  const secretError = requireSecret(secret)
  if (secretError) return secretError

  const items: string[] = []
  const tags = splitList(searchParams.get('tag'))
  const paths = splitList(searchParams.get('path'))

  for (const tag of tags) {
    revalidateTag(tag)
    items.push(`tag:${tag}`)
  }
  for (const path of paths) {
    revalidatePath(path)
    items.push(`path:${path}`)
  }

  if (tags.length === 0 && paths.length === 0) {
    revalidateAll(items)
  }

  return NextResponse.json({
    success: true,
    revalidated: true,
    items,
    count: items.length,
    timestamp: new Date().toISOString(),
  })
}
