/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    projects: Project;
    'project-categories': ProjectCategory;
    services: Service;
    testimonials: Testimonial;
    'team-members': TeamMember;
    'blog-posts': BlogPost;
    'blog-categories': BlogCategory;
    offices: Office;
    slider: Slider;
    'service-areas': ServiceArea;
    'google-reviews': GoogleReview;
    'cost-estimates': CostEstimate;
    'gallery-categories': GalleryCategory;
    'gallery-items': GalleryItem;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'project-categories': ProjectCategoriesSelect<false> | ProjectCategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    offices: OfficesSelect<false> | OfficesSelect<true>;
    slider: SliderSelect<false> | SliderSelect<true>;
    'service-areas': ServiceAreasSelect<false> | ServiceAreasSelect<true>;
    'google-reviews': GoogleReviewsSelect<false> | GoogleReviewsSelect<true>;
    'cost-estimates': CostEstimatesSelect<false> | CostEstimatesSelect<true>;
    'gallery-categories': GalleryCategoriesSelect<false> | GalleryCategoriesSelect<true>;
    'gallery-items': GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    home: Home;
    blog: Blog;
    about: About;
    portfolio: Portfolio;
    contact: Contact;
    'cost-estimator-settings': CostEstimatorSetting;
    'ceo-message': CeoMessage;
    'designers-page': DesignersPage;
    'success-stories-page': SuccessStoriesPage;
    'gallery-page': GalleryPage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    'cost-estimator-settings': CostEstimatorSettingsSelect<false> | CostEstimatorSettingsSelect<true>;
    'ceo-message': CeoMessageSelect<false> | CeoMessageSelect<true>;
    'designers-page': DesignersPageSelect<false> | DesignersPageSelect<true>;
    'success-stories-page': SuccessStoriesPageSelect<false> | SuccessStoriesPageSelect<true>;
    'gallery-page': GalleryPageSelect<false> | GalleryPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short, descriptive alt text for accessibility & SEO
   */
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    blur?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug?: string | null;
  category?: (number | null) | ProjectCategory;
  shortDescription?: string | null;
  year?: string | null;
  size?: string | null;
  location?: string | null;
  client?: string | null;
  seoDetails?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaKey?: string | null;
    /**
     * Image shown when page is shared on Facebook, WhatsApp, LinkedIn (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Paste valid JSON for structured data
     */
    seoStructuredData?: string | null;
  };
  featuredImage?: (number | null) | Media;
  /**
   * Check if this project should appear on the homepage
   */
  featuredOnHome?: boolean | null;
  /**
   * Check if this project parent is a residential project
   */
  isResidential?: boolean | null;
  /**
   * Check if this project parent is a commercial project
   */
  isCommercial?: boolean | null;
  /**
   * Check if this project parent is a architectural project
   */
  isArchitectural?: boolean | null;
  /**
   * Use for ordering projects on the homepage. Lower numbers appear first.
   */
  position?: number | null;
  /**
   * Use for ordering projects on the portfolio page. Lower numbers appear first.
   */
  portfolioPosition?: number | null;
  beforeAfterImages?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  details?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?: {
    photos?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    videos?:
      | {
          videoUrl?: string | null;
          id?: string | null;
        }[]
      | null;
    plans?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories".
 */
export interface ProjectCategory {
  id: number;
  title: string;
  slug?: string | null;
  pslug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL slug (e.g., residential-interior)
   */
  slug: string;
  shortDescription?: string | null;
  /**
   * Optional video link or embed code
   */
  introVideo?: string | null;
  ColorCode: string;
  hero?: {
    heroImage?: (number | null) | Media;
    title?: string | null;
    subtitle?: string | null;
  };
  introSection?: {
    sectionTitle?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  ourApproach?: {
    sectionTitle?: string | null;
    description?: string | null;
    approaches?:
      | {
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  recentProjects?: {
    sectionTitle?: string | null;
    sectionDescription?: string | null;
    projects?: (number | Project)[] | null;
  };
  seoDetails?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaKey?: string | null;
    /**
     * Image shown when page is shared on Facebook, WhatsApp, LinkedIn (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Paste valid JSON for structured data
     */
    seoStructuredData?: string | null;
  };
  /**
   * Keyword-rich content shown at the bottom of the page in a collapsible "Read More" section. Helps Google understand what this page is about. Supports H1–H6, paragraphs, lists, blockquote, and more.
   */
  seoContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  title: string;
  shortDetails?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Paste the video URL (YouTube, Vimeo, etc.)
   */
  videoUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * Auto-generated from the name. Used for the bio page URL (/our-designers/<slug>).
   */
  slug?: string | null;
  designation?: string | null;
  licenseNumber?: string | null;
  photo?: (number | null) | Media;
  photoUrl?: string | null;
  /**
   * One- or two-line summary shown on the team listing card and at the top of the bio page.
   */
  shortBio?: string | null;
  /**
   * Full bio shown on the member's individual page. Supports headings, bold, lists, links.
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Skill / focus tags shown as chips on the bio page.
   */
  specialties?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional LinkedIn profile URL (shown + used for Person schema sameAs).
   */
  linkedinUrl?: string | null;
  /**
   * Display order on the team page. Lower numbers appear first (CEO = 1).
   */
  position?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * Auto-generated from the title. You can override it manually.
   */
  slug?: string | null;
  featuredImage?: (number | null) | Media;
  shortDescription?: string | null;
  fullContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category: number | BlogCategory;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedDate: string;
  seoDetails?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaKey?: string | null;
    /**
     * Image shown when page is shared on Facebook, WhatsApp, LinkedIn (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Paste valid JSON for structured data
     */
    seoStructuredData?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offices".
 */
export interface Office {
  id: number;
  title: string;
  address: string;
  latitude?: number | null;
  longitude?: number | null;
  phone?: string | null;
  email?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slider".
 */
export interface Slider {
  id: number;
  slider?: {
    image?: (number | null) | Media;
    title?: string | null;
    subtitle?: string | null;
    position?: string | null;
    ctaButton1?: {
      label?: string | null;
      url?: string | null;
    };
    ctaButton2?: {
      label?: string | null;
      url?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas".
 */
export interface ServiceArea {
  id: number;
  areaName: string;
  slug: string;
  fullContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Paste Google Maps iframe embed code
   */
  googleEmbedCode?: string | null;
  seoDetails?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaKey?: string | null;
    /**
     * Image shown when page is shared on Facebook, WhatsApp, LinkedIn (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Paste valid JSON for structured data
     */
    seoStructuredData?: string | null;
  };
  /**
   * Keyword-rich content shown at the bottom of the page in a collapsible "Read More" section. Helps Google understand what this page is about. Supports H1–H6, paragraphs, lists, blockquote, and more.
   */
  seoContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-reviews".
 */
export interface GoogleReview {
  id: number;
  reviewerName: string;
  /**
   * Optional profile photo of the reviewer
   */
  reviewerPhoto?: (number | null) | Media;
  /**
   * Star rating (1-5)
   */
  rating: number;
  reviewText: string;
  reviewDate?: string | null;
  /**
   * Display order (lower numbers appear first)
   */
  position?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Leads submitted through the public Cost Estimator wizard at /cost-estimator. Estimated values are calculated server-side from current admin rates.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cost-estimates".
 */
export interface CostEstimate {
  id: number;
  name: string;
  phone: string;
  /**
   * Optional.
   */
  email?: string | null;
  /**
   * Free-form, e.g. "Banani, Dhaka".
   */
  location?: string | null;
  smsConsent?: boolean | null;
  projectType: 'full-home' | 'single-room' | 'office' | 'commercial';
  flatStatus?: ('ready' | 'not-ready' | 'under-construction') | null;
  city: 'dhaka-prime' | 'dhaka-other' | 'chittagong' | 'sylhet' | 'other';
  packageTier: 'standard' | 'premium' | 'signature';
  /**
   * Rooms the user selected on Step 3.
   */
  rooms?:
    | {
        roomType: 'living-room' | 'kitchen' | 'bedroom' | 'bathroom' | 'dining' | 'foyer' | 'family-living' | 'study';
        count: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Add-on keys the user selected on Step 4.
   */
  addOns?:
    | {
        key: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Computed total area in sft (server-calculated).
   */
  totalSft?: number | null;
  notes?: string | null;
  estimatedMinBdt: number;
  estimatedMaxBdt: number;
  status?: ('new' | 'contacted' | 'qualified' | 'quoted' | 'converted' | 'lost') | null;
  pageUrl?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Categories for the public /gallery page. Gallery items are assigned to these categories and shown as filter tabs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories".
 */
export interface GalleryCategory {
  id: number;
  title: string;
  /**
   * Order of the category filter buttons. Lower numbers appear first.
   */
  position?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photos and videos shown on the public /gallery page, organised by Gallery Category. Each item can optionally link to a page (e.g. a portfolio project).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items".
 */
export interface GalleryItem {
  id: number;
  title: string;
  category: number | GalleryCategory;
  mediaType: 'photo' | 'video';
  /**
   * The photo to display.
   */
  image?: (number | null) | Media;
  /**
   * YouTube video URL (e.g. https://youtu.be/...).
   */
  videoUrl?: string | null;
  /**
   * Optional. Where the item title links to — internal path (e.g. /portfolio/some-project) or full URL.
   */
  link?: string | null;
  /**
   * Display order within the gallery. Lower numbers appear first.
   */
  position?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'project-categories';
        value: number | ProjectCategory;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'offices';
        value: number | Office;
      } | null)
    | ({
        relationTo: 'slider';
        value: number | Slider;
      } | null)
    | ({
        relationTo: 'service-areas';
        value: number | ServiceArea;
      } | null)
    | ({
        relationTo: 'google-reviews';
        value: number | GoogleReview;
      } | null)
    | ({
        relationTo: 'cost-estimates';
        value: number | CostEstimate;
      } | null)
    | ({
        relationTo: 'gallery-categories';
        value: number | GalleryCategory;
      } | null)
    | ({
        relationTo: 'gallery-items';
        value: number | GalleryItem;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        blur?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  shortDescription?: T;
  year?: T;
  size?: T;
  location?: T;
  client?: T;
  seoDetails?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKey?: T;
        ogImage?: T;
        seoStructuredData?: T;
      };
  featuredImage?: T;
  featuredOnHome?: T;
  isResidential?: T;
  isCommercial?: T;
  isArchitectural?: T;
  position?: T;
  portfolioPosition?: T;
  beforeAfterImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  details?: T;
  gallery?:
    | T
    | {
        photos?:
          | T
          | {
              image?: T;
              id?: T;
            };
        videos?:
          | T
          | {
              videoUrl?: T;
              id?: T;
            };
        plans?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories_select".
 */
export interface ProjectCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pslug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  introVideo?: T;
  ColorCode?: T;
  hero?:
    | T
    | {
        heroImage?: T;
        title?: T;
        subtitle?: T;
      };
  introSection?:
    | T
    | {
        sectionTitle?: T;
        description?: T;
      };
  ourApproach?:
    | T
    | {
        sectionTitle?: T;
        description?: T;
        approaches?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  recentProjects?:
    | T
    | {
        sectionTitle?: T;
        sectionDescription?: T;
        projects?: T;
      };
  seoDetails?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKey?: T;
        ogImage?: T;
        seoStructuredData?: T;
      };
  seoContent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  title?: T;
  shortDetails?: T;
  coverImage?: T;
  videoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  designation?: T;
  licenseNumber?: T;
  photo?: T;
  photoUrl?: T;
  shortBio?: T;
  bio?: T;
  specialties?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  linkedinUrl?: T;
  position?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featuredImage?: T;
  shortDescription?: T;
  fullContent?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedDate?: T;
  seoDetails?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKey?: T;
        ogImage?: T;
        seoStructuredData?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offices_select".
 */
export interface OfficesSelect<T extends boolean = true> {
  title?: T;
  address?: T;
  latitude?: T;
  longitude?: T;
  phone?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slider_select".
 */
export interface SliderSelect<T extends boolean = true> {
  slider?:
    | T
    | {
        image?: T;
        title?: T;
        subtitle?: T;
        position?: T;
        ctaButton1?:
          | T
          | {
              label?: T;
              url?: T;
            };
        ctaButton2?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas_select".
 */
export interface ServiceAreasSelect<T extends boolean = true> {
  areaName?: T;
  slug?: T;
  fullContent?: T;
  googleEmbedCode?: T;
  seoDetails?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKey?: T;
        ogImage?: T;
        seoStructuredData?: T;
      };
  seoContent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-reviews_select".
 */
export interface GoogleReviewsSelect<T extends boolean = true> {
  reviewerName?: T;
  reviewerPhoto?: T;
  rating?: T;
  reviewText?: T;
  reviewDate?: T;
  position?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cost-estimates_select".
 */
export interface CostEstimatesSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  location?: T;
  smsConsent?: T;
  projectType?: T;
  flatStatus?: T;
  city?: T;
  packageTier?: T;
  rooms?:
    | T
    | {
        roomType?: T;
        count?: T;
        id?: T;
      };
  addOns?:
    | T
    | {
        key?: T;
        label?: T;
        id?: T;
      };
  totalSft?: T;
  notes?: T;
  estimatedMinBdt?: T;
  estimatedMaxBdt?: T;
  status?: T;
  pageUrl?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories_select".
 */
export interface GalleryCategoriesSelect<T extends boolean = true> {
  title?: T;
  position?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  mediaType?: T;
  image?: T;
  videoUrl?: T;
  link?: T;
  position?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Big footer heading. Line breaks are preserved.
   */
  headline?: string | null;
  quickLinks?: {
    title?: string | null;
    /**
     * Leave empty to use the built-in defaults.
     */
    links?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  importantLinks?: {
    title?: string | null;
    /**
     * Leave empty to use the built-in defaults.
     */
    links?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  contactTitle?: string | null;
  serviceAreasTitle?: string | null;
  /**
   * Text after the © year. Leave empty to use the site name from Site Settings.
   */
  copyrightText?: string | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  featuredWorks?: {
    sectionTitle?: string | null;
    sectionDescription?: string | null;
    backgroundColor?: string | null;
  };
  aboutSection?: {
    sectionTitle?: string | null;
    shortDescription?: string | null;
    beforeAfterImages?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    highlights?:
      | {
          text?: string | null;
          desc?: string | null;
          id?: string | null;
        }[]
      | null;
    backgroundColor?: string | null;
  };
  servicesSection?: {
    /**
     * The last word is rendered in the accent color.
     */
    sectionTitle?: string | null;
    shortDescription?: string | null;
    /**
     * The 3 service cards. Leave empty to use the built-in defaults. Icon and hover video are optional.
     */
    cards?:
      | {
          title: string;
          description?: string | null;
          /**
           * e.g. /services/residential-interior
           */
          link?: string | null;
          icon?: (number | null) | Media;
          /**
           * Optional background video shown on hover, e.g. /videos/residential.mp4
           */
          videoUrl?: string | null;
          id?: string | null;
        }[]
      | null;
    services?: (number | Service)[] | null;
    backgroundColor?: string | null;
  };
  ourProcess?: {
    /**
     * The last word is rendered in the accent color.
     */
    sectionTitle?: string | null;
    shortDescription?: string | null;
    /**
     * Process steps. Leave empty to use the built-in 5 defaults.
     */
    steps?:
      | {
          icon?: (number | null) | Media;
          title?: string | null;
          description?: string | null;
          /**
           * Accent color hex, e.g. #6366F1. Optional.
           */
          color?: string | null;
          id?: string | null;
        }[]
      | null;
    backgroundColor?: string | null;
  };
  clientStories?: {
    /**
     * The last word is rendered in the accent color.
     */
    sectionTitle?: string | null;
    shortDescription?: string | null;
    testimonials?: (number | Testimonial)[] | null;
    backgroundColor?: string | null;
  };
  blogSection?: {
    sectionLabel?: string | null;
    /**
     * The last word is rendered in the accent color.
     */
    sectionTitle?: string | null;
    viewAllLabel?: string | null;
    viewAllUrl?: string | null;
  };
  ctaSection?: {
    title?: string | null;
    /**
     * This word inside the title is rendered in the accent color.
     */
    highlightWord?: string | null;
    description?: string | null;
    primaryButtonLabel?: string | null;
    primaryButtonUrl?: string | null;
    secondaryButtonLabel?: string | null;
    secondaryButtonUrl?: string | null;
  };
  googleReviews?: {
    sectionTitle?: string | null;
    shortDescription?: string | null;
    /**
     * Overall Google rating (e.g. 4.8)
     */
    overallRating?: number | null;
    /**
     * Total number of Google reviews
     */
    totalReviews?: number | null;
    /**
     * Link to your Google Business review page
     */
    googleReviewUrl?: string | null;
    backgroundColor?: string | null;
  };
  faqSection?: {
    sectionLabel?: string | null;
    /**
     * First part of the heading (rendered in dark text)
     */
    titlePrimary?: string | null;
    /**
     * Highlighted part of the heading (rendered in accent color)
     */
    titleHighlight?: string | null;
    description?: string | null;
    viewAllLabel?: string | null;
    viewAllUrl?: string | null;
    askDirectlyLabel?: string | null;
    askDirectlyUrl?: string | null;
    /**
     * FAQs displayed on the home page. The first FAQ is open by default. Also used to render FAQPage JSON-LD for SEO.
     */
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  seoDetails?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaKey?: string | null;
    /**
     * Paste valid JSON for structured data
     */
    seoStructuredData?: string | null;
  };
  /**
   * Keyword-rich content shown at the bottom of the home page in a collapsible "Read More" section. Helps Google understand what this page is about. Supports H1–H6, paragraphs, lists, blockquote, and more.
   */
  seoContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  hero?: {
    heroImage?: (number | null) | Media;
    title?: string | null;
    subtitle?: string | null;
  };
  introText?: string | null;
  seoDetails?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaKey?: string | null;
    /**
     * Paste valid JSON for structured data
     */
    seoStructuredData?: string | null;
  };
  /**
   * Keyword-rich content shown at the bottom of the page in a collapsible "Read More" section. Helps Google understand what this page is about. Supports H1–H6, paragraphs, lists, blockquote, and more.
   */
  seoContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  hero: {
    heroImage: number | Media;
    title?: string | null;
    subtitle?: string | null;
  };
  introSection?: {
    sectionTitle?: string | null;
    description?: string | null;
    introVideo?: string | null;
    stats?:
      | {
          label?: string | null;
          value?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  ourApproach?: {
    sectionTitle?: string | null;
    description?: string | null;
    approaches?:
      | {
          icon?: (number | null) | Media;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  missionVision?: {
    sectionTitle?: string | null;
    description?: string | null;
    missionContent?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    visionContent?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  teamSection?: {
    sectionTitle?: string | null;
    description?: string | null;
    teamMembers?: (number | TeamMember)[] | null;
  };
  seoDetails?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaKey?: string | null;
    /**
     * Paste valid JSON for structured data
     */
    seoStructuredData?: string | null;
  };
  /**
   * Keyword-rich content shown at the bottom of the page in a collapsible "Read More" section. Helps Google understand what this page is about. Supports H1–H6, paragraphs, lists, blockquote, and more.
   */
  seoContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: number;
  hero?: {
    heroImage?: (number | null) | Media;
    title?: string | null;
    subtitle?: string | null;
  };
  introText?: string | null;
  seoDetails?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaKey?: string | null;
    /**
     * Paste valid JSON for structured data
     */
    seoStructuredData?: string | null;
  };
  /**
   * Keyword-rich content shown at the bottom of the page in a collapsible "Read More" section. Helps Google understand what this page is about. Supports H1–H6, paragraphs, lists, blockquote, and more.
   */
  seoContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  hero?: {
    heroImage?: (number | null) | Media;
    title?: string | null;
    subtitle?: string | null;
  };
  introText?: string | null;
  offices?: (number | Office)[] | null;
  seoDetails?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaKey?: string | null;
    /**
     * Paste valid JSON for structured data
     */
    seoStructuredData?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls everything on the public Cost Estimator wizard at /cost-estimator. Changes go live within seconds — no rebuild required.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cost-estimator-settings".
 */
export interface CostEstimatorSetting {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  welcomeButtonLabel?: string | null;
  finalButtonLabel?: string | null;
  disclaimer?: string | null;
  resultTitle?: string | null;
  resultSubtitle?: string | null;
  standardLow: number;
  standardHigh: number;
  premiumLow: number;
  premiumHigh: number;
  signatureLow: number;
  signatureHigh: number;
  cityMultiplierDhakaPrime: number;
  cityMultiplierDhakaOther: number;
  cityMultiplierChittagong: number;
  cityMultiplierSylhet: number;
  cityMultiplierOther: number;
  projectTypeMultiplierResidential: number;
  projectTypeMultiplierSingleRoom: number;
  projectTypeMultiplierOffice: number;
  projectTypeMultiplierCommercial: number;
  sftLivingRoom: number;
  sftKitchen: number;
  sftBedroom: number;
  sftBathroom: number;
  sftDining: number;
  sftFoyer: number;
  sftFamilyLiving: number;
  sftStudy: number;
  /**
   * Add or remove add-ons. Each is shown as a checkbox under the relevant room on Step 4.
   */
  addOns?:
    | {
        /**
         * e.g. wooden-ceiling-living
         */
        key: string;
        label: string;
        roomScope:
          | 'living-room'
          | 'kitchen'
          | 'bedroom'
          | 'bathroom'
          | 'dining'
          | 'foyer'
          | 'family-living'
          | 'study'
          | 'whole-project';
        priceStandard: number;
        pricePremium: number;
        priceSignature: number;
        id?: string | null;
      }[]
    | null;
  packageStandard?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    features?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
  };
  packagePremium?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    features?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
  };
  packageSignature?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    features?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
  };
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the public "Message from CEO" page at /message-from-ceo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ceo-message".
 */
export interface CeoMessage {
  id: number;
  hero?: {
    title?: string | null;
    heroImage?: (number | null) | Media;
  };
  ceoName?: string | null;
  ceoTitle?: string | null;
  /**
   * Small stat highlights shown under the CEO photo (e.g. 9+ Years of Experience). 2–3 work best.
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Portrait photo shown beside the message.
   */
  ceoPhoto?: (number | null) | Media;
  /**
   * Short pull-quote highlighted at the top of the message.
   */
  quote?: string | null;
  /**
   * The full CEO message. Supports headings, bold, lists, etc.
   */
  message?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional signature image shown below the message.
   */
  signatureImage?: (number | null) | Media;
  seoDetails?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Page copy for /our-designers. The designers themselves are managed in the "Team Members" collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designers-page".
 */
export interface DesignersPage {
  id: number;
  hero?: {
    title?: string | null;
    heroImage?: (number | null) | Media;
  };
  introText?: string | null;
  seoDetails?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Page copy for /client-success-stories. Video testimonials are managed in the "Testimonials" collection; written reviews in "Google Reviews".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories-page".
 */
export interface SuccessStoriesPage {
  id: number;
  hero?: {
    title?: string | null;
    heroImage?: (number | null) | Media;
  };
  introText?: string | null;
  videosSectionTitle?: string | null;
  reviewsSectionTitle?: string | null;
  seoDetails?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Page copy for /gallery. Photos and videos are pulled automatically from the galleries of all Projects, grouped by Project Category.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page".
 */
export interface GalleryPage {
  id: number;
  hero?: {
    title?: string | null;
    heroImage?: (number | null) | Media;
  };
  introText?: string | null;
  seoDetails?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Global branding & business info: site name, contact details, address, social links. Used across the whole site (SEO, structured data, footer, contact page).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brand: {
    name: string;
    /**
     * Short tagline used as OG image subtitle and title suffix.
     */
    tagline?: string | null;
    /**
     * Default meta/OG description and JSON-LD business description.
     */
    description?: string | null;
  };
  contact?: {
    phone?: string | null;
    whatsapp?: string | null;
    email?: string | null;
  };
  address?: {
    streetAddress?: string | null;
    addressLocality?: string | null;
    addressRegion?: string | null;
    postalCode?: string | null;
    addressCountry?: string | null;
    /**
     * Full address as one line, shown on the contact page.
     */
    full?: string | null;
  };
  geo?: {
    latitude?: number | null;
    longitude?: number | null;
    /**
     * Google Maps link to the business location.
     */
    hasMap?: string | null;
  };
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
    pinterest?: string | null;
  };
  business?: {
    /**
     * schema.org format, e.g. "Mo-Sa 10:00-19:00".
     */
    openingHours?: string | null;
    priceRange?: string | null;
    areaServed?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  headline?: T;
  quickLinks?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  importantLinks?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  contactTitle?: T;
  serviceAreasTitle?: T;
  copyrightText?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  featuredWorks?:
    | T
    | {
        sectionTitle?: T;
        sectionDescription?: T;
        backgroundColor?: T;
      };
  aboutSection?:
    | T
    | {
        sectionTitle?: T;
        shortDescription?: T;
        beforeAfterImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        highlights?:
          | T
          | {
              text?: T;
              desc?: T;
              id?: T;
            };
        backgroundColor?: T;
      };
  servicesSection?:
    | T
    | {
        sectionTitle?: T;
        shortDescription?: T;
        cards?:
          | T
          | {
              title?: T;
              description?: T;
              link?: T;
              icon?: T;
              videoUrl?: T;
              id?: T;
            };
        services?: T;
        backgroundColor?: T;
      };
  ourProcess?:
    | T
    | {
        sectionTitle?: T;
        shortDescription?: T;
        steps?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              color?: T;
              id?: T;
            };
        backgroundColor?: T;
      };
  clientStories?:
    | T
    | {
        sectionTitle?: T;
        shortDescription?: T;
        testimonials?: T;
        backgroundColor?: T;
      };
  blogSection?:
    | T
    | {
        sectionLabel?: T;
        sectionTitle?: T;
        viewAllLabel?: T;
        viewAllUrl?: T;
      };
  ctaSection?:
    | T
    | {
        title?: T;
        highlightWord?: T;
        description?: T;
        primaryButtonLabel?: T;
        primaryButtonUrl?: T;
        secondaryButtonLabel?: T;
        secondaryButtonUrl?: T;
      };
  googleReviews?:
    | T
    | {
        sectionTitle?: T;
        shortDescription?: T;
        overallRating?: T;
        totalReviews?: T;
        googleReviewUrl?: T;
        backgroundColor?: T;
      };
  faqSection?:
    | T
    | {
        sectionLabel?: T;
        titlePrimary?: T;
        titleHighlight?: T;
        description?: T;
        viewAllLabel?: T;
        viewAllUrl?: T;
        askDirectlyLabel?: T;
        askDirectlyUrl?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  seoDetails?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKey?: T;
        seoStructuredData?: T;
      };
  seoContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heroImage?: T;
        title?: T;
        subtitle?: T;
      };
  introText?: T;
  seoDetails?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKey?: T;
        seoStructuredData?: T;
      };
  seoContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heroImage?: T;
        title?: T;
        subtitle?: T;
      };
  introSection?:
    | T
    | {
        sectionTitle?: T;
        description?: T;
        introVideo?: T;
        stats?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  ourApproach?:
    | T
    | {
        sectionTitle?: T;
        description?: T;
        approaches?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  missionVision?:
    | T
    | {
        sectionTitle?: T;
        description?: T;
        missionContent?: T;
        visionContent?: T;
      };
  teamSection?:
    | T
    | {
        sectionTitle?: T;
        description?: T;
        teamMembers?: T;
      };
  seoDetails?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKey?: T;
        seoStructuredData?: T;
      };
  seoContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heroImage?: T;
        title?: T;
        subtitle?: T;
      };
  introText?: T;
  seoDetails?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKey?: T;
        seoStructuredData?: T;
      };
  seoContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heroImage?: T;
        title?: T;
        subtitle?: T;
      };
  introText?: T;
  offices?: T;
  seoDetails?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKey?: T;
        seoStructuredData?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cost-estimator-settings_select".
 */
export interface CostEstimatorSettingsSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  welcomeButtonLabel?: T;
  finalButtonLabel?: T;
  disclaimer?: T;
  resultTitle?: T;
  resultSubtitle?: T;
  standardLow?: T;
  standardHigh?: T;
  premiumLow?: T;
  premiumHigh?: T;
  signatureLow?: T;
  signatureHigh?: T;
  cityMultiplierDhakaPrime?: T;
  cityMultiplierDhakaOther?: T;
  cityMultiplierChittagong?: T;
  cityMultiplierSylhet?: T;
  cityMultiplierOther?: T;
  projectTypeMultiplierResidential?: T;
  projectTypeMultiplierSingleRoom?: T;
  projectTypeMultiplierOffice?: T;
  projectTypeMultiplierCommercial?: T;
  sftLivingRoom?: T;
  sftKitchen?: T;
  sftBedroom?: T;
  sftBathroom?: T;
  sftDining?: T;
  sftFoyer?: T;
  sftFamilyLiving?: T;
  sftStudy?: T;
  addOns?:
    | T
    | {
        key?: T;
        label?: T;
        roomScope?: T;
        priceStandard?: T;
        pricePremium?: T;
        priceSignature?: T;
        id?: T;
      };
  packageStandard?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
      };
  packagePremium?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
      };
  packageSignature?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ceo-message_select".
 */
export interface CeoMessageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        heroImage?: T;
      };
  ceoName?: T;
  ceoTitle?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  ceoPhoto?: T;
  quote?: T;
  message?: T;
  signatureImage?: T;
  seoDetails?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designers-page_select".
 */
export interface DesignersPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        heroImage?: T;
      };
  introText?: T;
  seoDetails?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories-page_select".
 */
export interface SuccessStoriesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        heroImage?: T;
      };
  introText?: T;
  videosSectionTitle?: T;
  reviewsSectionTitle?: T;
  seoDetails?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page_select".
 */
export interface GalleryPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        heroImage?: T;
      };
  introText?: T;
  seoDetails?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        name?: T;
        tagline?: T;
        description?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        whatsapp?: T;
        email?: T;
      };
  address?:
    | T
    | {
        streetAddress?: T;
        addressLocality?: T;
        addressRegion?: T;
        postalCode?: T;
        addressCountry?: T;
        full?: T;
      };
  geo?:
    | T
    | {
        latitude?: T;
        longitude?: T;
        hasMap?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        youtube?: T;
        pinterest?: T;
      };
  business?:
    | T
    | {
        openingHours?: T;
        priceRange?: T;
        areaServed?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}